const RESOURCE_SEED = [
  {
    id: 1,
    name: 'Computer Lab A',
    type: 'lab',
    building: 'Tech Block',
    floor: '2nd',
    capacity: 40,
    amenities: ['Projector', 'AC', 'Wi-Fi', 'Whiteboard'],
    status: 'active',
  },
  {
    id: 2,
    name: 'Computer Lab B',
    type: 'lab',
    building: 'Tech Block',
    floor: '2nd',
    capacity: 35,
    amenities: ['Projector', 'AC', 'Wi-Fi'],
    status: 'active',
  },
  {
    id: 3,
    name: 'Physics Lab',
    type: 'lab',
    building: 'Science Block',
    floor: '1st',
    capacity: 30,
    amenities: ['AC', 'Instruments'],
    status: 'active',
  },
  {
    id: 4,
    name: 'Chemistry Lab',
    type: 'lab',
    building: 'Science Block',
    floor: '1st',
    capacity: 25,
    amenities: ['AC', 'Fume Hood', 'Safety Gear'],
    status: 'active',
  },
  {
    id: 5,
    name: 'Electronics Lab',
    type: 'lab',
    building: 'Tech Block',
    floor: '3rd',
    capacity: 30,
    amenities: ['Oscilloscopes', 'AC'],
    status: 'active',
  },
  {
    id: 6,
    name: 'Biology Lab',
    type: 'lab',
    building: 'Science Block',
    floor: '2nd',
    capacity: 28,
    amenities: ['Microscopes', 'AC'],
    status: 'active',
  },
  {
    id: 7,
    name: 'Robotics Lab',
    type: 'lab',
    building: 'Innovation Hub',
    floor: '1st',
    capacity: 20,
    amenities: ['3D Printers', 'Tools'],
    status: 'active',
  },
  {
    id: 8,
    name: 'AI Research Lab',
    type: 'lab',
    building: 'Innovation Hub',
    floor: '2nd',
    capacity: 15,
    amenities: ['GPUs', 'Wi-Fi'],
    status: 'active',
  },
  {
    id: 9,
    name: 'Design Studio',
    type: 'lab',
    building: 'Arts Block',
    floor: '1st',
    capacity: 25,
    amenities: ['iMacs', 'Tablets'],
    status: 'active',
  },
  {
    id: 10,
    name: 'Network Lab',
    type: 'lab',
    building: 'Tech Block',
    floor: '3rd',
    capacity: 20,
    amenities: ['Routers', 'Switches'],
    status: 'active',
  },
  {
    id: 11,
    name: 'Main Auditorium',
    type: 'hall',
    building: 'Central Block',
    floor: 'Ground',
    capacity: 500,
    amenities: ['Projector', 'Sound System', 'Stage'],
    status: 'active',
  },
  {
    id: 12,
    name: 'Mini Auditorium',
    type: 'hall',
    building: 'Central Block',
    floor: '1st',
    capacity: 150,
    amenities: ['Projector', 'Sound System'],
    status: 'active',
  },
  {
    id: 13,
    name: 'Conference Hall',
    type: 'hall',
    building: 'Admin Block',
    floor: '3rd',
    capacity: 80,
    amenities: ['Video Conf', 'Whiteboard'],
    status: 'active',
  },
];

const MARKETPLACE_SEED = [
  {
    id: 'mkt_1',
    sellerId: 'usr_seed_1',
    sellerName: 'Priya Mehta',
    sellerVerified: true,
    sellerTrustScore: 4.8,
    title: 'Data Structures by Cormen (CLRS)',
    category: 'books',
    description: '3rd edition, minor highlights. Perfect for CS students preparing for interviews.',
    price: 450,
    condition: 'good',
    status: 'active',
    image: '/marketplace/textbook.png',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_2',
    sellerId: 'usr_seed_2',
    sellerName: 'Rahul Kumar',
    sellerVerified: true,
    sellerTrustScore: 4.9,
    title: 'HP Scientific Calculator',
    category: 'electronics',
    description: 'HP 35s. Used for one semester. In excellent working condition with original box.',
    price: 800,
    condition: 'like_new',
    status: 'active',
    image: '/marketplace/calculator.png',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_3',
    sellerId: 'usr_seed_3',
    sellerName: 'Nisha Gupta',
    sellerVerified: true,
    sellerTrustScore: 4.4,
    title: 'College Hoodie (2024)',
    category: 'clothing',
    description: 'Size L. Official merchandise. Never worn, brand new with tags.',
    price: 600,
    condition: 'new',
    status: 'active',
    image: '/marketplace/hoodie.png',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_4',
    sellerId: 'usr_seed_1',
    sellerName: 'Priya Mehta',
    sellerVerified: true,
    sellerTrustScore: 4.8,
    title: 'Adjustable Laptop Stand',
    category: 'accessories',
    description: 'Aluminium foldable laptop stand with adjustable height. Fits 10-17" laptops.',
    price: 550,
    condition: 'like_new',
    status: 'active',
    image: null,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_5',
    sellerId: 'usr_seed_2',
    sellerName: 'Rahul Kumar',
    sellerVerified: true,
    sellerTrustScore: 4.9,
    title: 'Chemistry Lab Coat',
    category: 'clothing',
    description: 'White lab coat, Size M. Used for 1 semester, still in great condition.',
    price: 200,
    condition: 'good',
    status: 'active',
    image: null,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_6',
    sellerId: 'usr_seed_3',
    sellerName: 'Nisha Gupta',
    sellerVerified: true,
    sellerTrustScore: 4.4,
    title: 'boAt Earbuds Airdopes 141',
    category: 'electronics',
    description: 'Wireless Bluetooth earbuds with charging case. 6 months old, excellent battery life.',
    price: 700,
    condition: 'good',
    status: 'active',
    image: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_7',
    sellerId: 'usr_seed_1',
    sellerName: 'Priya Mehta',
    sellerVerified: true,
    sellerTrustScore: 4.8,
    title: 'Yoga Mat (6mm)',
    category: 'sports',
    description: 'Anti-slip yoga mat, barely used. Great for hostel room workouts.',
    price: 350,
    condition: 'like_new',
    status: 'active',
    image: null,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt_8',
    sellerId: 'usr_seed_2',
    sellerName: 'Rahul Kumar',
    sellerVerified: true,
    sellerTrustScore: 4.9,
    title: 'Hand-Written Notes Bundle (Physics)',
    category: 'notes',
    description: 'Complete notes for Engineering Physics — covers all 5 modules with solved numericals.',
    price: 150,
    condition: 'good',
    status: 'active',
    image: null,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
];

const LOST_FOUND_SEED = [
  {
    id: 'lf_1',
    reporterId: 'usr_seed_1',
    reporterName: 'Priya M.',
    type: 'lost',
    title: 'Blue Water Bottle (Milton)',
    description: 'Left on table near window around 3 PM.',
    location: 'Library 2nd Floor',
    tags: ['water bottle', 'blue', 'milton'],
    status: 'active',
    image: null,
    dateReported: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lf_2',
    reporterId: 'usr_seed_2',
    reporterName: 'Rahul K.',
    type: 'found',
    title: 'Graphing Calculator (Casio)',
    description: 'Found under desk after 2 PM class.',
    location: 'Computer Lab A',
    tags: ['calculator', 'casio'],
    status: 'active',
    image: null,
    dateReported: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lf_3',
    reporterId: 'usr_seed_3',
    reporterName: 'Ankit S.',
    type: 'lost',
    title: 'Student ID Card',
    description: 'Lost in cafeteria during lunch.',
    location: 'Cafeteria',
    tags: ['id card', 'identity'],
    status: 'active',
    image: null,
    dateReported: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)
      .toISOString()
      .slice(0, 10),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

const BOOKING_SEED = [
  {
    id: 'bk_1',
    userId: 'usr_seed_1',
    userName: 'Priya Mehta',
    userEmail: 'priya@campus.edu',
    resourceId: 1,
    date: new Date().toISOString().slice(0, 10),
    startTime: '10:00',
    endTime: '12:00',
    purpose: 'Data Structures Lab',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bk_2',
    userId: 'usr_seed_2',
    userName: 'Rahul Kumar',
    userEmail: 'rahul@campus.edu',
    resourceId: 11,
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    startTime: '11:00',
    endTime: '13:00',
    purpose: 'Tech Club Seminar',
    status: 'pending',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

const USER_SEED = [
  {
    id: 'usr_seed_1',
    email: 'priya@campus.edu',
    name: 'Priya Mehta',
    verified: true,
    trustScore: 4.8,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'usr_seed_2',
    email: 'rahul@campus.edu',
    name: 'Rahul Kumar',
    verified: true,
    trustScore: 4.9,
    createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLogin: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'usr_seed_3',
    email: 'nisha@campus.edu',
    name: 'Nisha Gupta',
    verified: true,
    trustScore: 4.4,
    createdAt: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLogin: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export function createSeedState() {
  return {
    users: USER_SEED,
    otpCodes: [],
    resources: RESOURCE_SEED,
    bookings: BOOKING_SEED,
    marketplaceListings: MARKETPLACE_SEED,
    lostFoundItems: LOST_FOUND_SEED,
  };
}
